### ISSUE TITLE
Image not accessible

### ISSUE THREAD

**Issue by NicolasT** [redhat-cop/keepalived-operator#14]
I tried to pull the `keepalived` image as used by the operator (`docker pull registry.redhat.io/openshift4/ose-keepalived-ipfailover`). However, it appears one needs Red Hat Registry credentials to do so (which I don't have, AFAIK). Would it be possible to either use a public image, or (even better?) include a/the `Dockerfile` to build such image?

**Comment by raffaelespazzoli** [comment]
I believe it should be possible. This images would be a good publicly accessible replacement:
`https://quay.io/repository/openshift/origin-keepalived-ipfailover`
An operator option should be provided to supply an different image image.
In the meantime, you can find the template of what is deployed at this location in the operator image: `/templates`. 
There you can patch with the image you want and run your tests.

**Comment by raffaelespazzoli** [comment]
closed by #22
