### ISSUE TITLE
Add disclaimer about support from Red Hat

### ISSUE THREAD

**Issue by soukron** [redhat-cop/keepalived-operator#18]
Some users are landing in this repository after reading some recommendations about using this operator for their ExternalIPs and are concerned about the support about it.

It would be very helpful if you can add a disclaimer at the top of the README to say that this repository and the code is considered a 3rd party software and therefore it's not supported by Red Hat and that any issue with it should be reported in this Issues page.

**Comment by kanekoh** [comment]
Hello, I have the same issue. 
I have a customer who use ipfailover on OCP 3.11 and have planned to migrate to OCP 4.x. But I haven't found any ways which is supported by Red Hat for ipfailover. I wonder if this feature will be promoted to an official Operator in OperatorHub.

**Comment by raffaelespazzoli** [comment]
@soukron there is nothing here that should make someone believe that this is supported by red hat. This is also well specified ib operator hub
@kanekoh if you want support for this operator, which I think it would be a good idea, your customer has to lobby for that to red hat. One way to do it is to open a case. By the way, this operator is in operator hub in the community section.

**Comment by soukron** [comment]
Can't you see how contradictory are your words? On one side you tell me that "nothing should make someone believe that this is supported by Red Hat" (but the repository is named redhat-cop) and on the other side you tell to @kanekoh that if customers want support "they must lobby for that to Red Hat". 

At least a disclaimer would be nice to avoid confusions and discussions with disappointed customers which think that it's supported (from their point of view, they got an operator from a Red Hat's git repository where the members are Red Hat employees) and then they get a negative and a link to the [scope of support](https://access.redhat.com/support/offerings/production/soc) link where they can see that Red Hat doesn't provides support to 3rd party software and/or community projects. 

Let's prevent disappointed and angry customers. Let's be clear from the begging that they're using code not supported by Red Hat. Don't you think?

**Comment by Zefool** [comment]
I agree that a short disclaimer is a good idea. 

A question to help in your ( @raffaelespazzoli ) decision:
Is there a reason to **not** have a disclaimer at the top of the README?

**Comment by Zefool** [comment]
I made a quick PR with a suggestion. Feel free to edit, replace or reject, whatever you like.
