### ISSUE TITLE
Allow configuration of router_virtual_id

### ISSUE THREAD

**Issue by David-Igou** [redhat-cop/keepalived-operator#26]
If the cluster keepalived-operator is deployed on shares an environment with other instances of keepalived, it is possible for conflicts to happen. Operators should be able to override `router_virtual_id` to prevent this from happening

By default router_virtual_id always starts with "1" as VIPs are assigned, and this cannot be configured. If `router_virtual_id` is set by adding annotation `keepalived-operator.redhat-cop.io/verbatimconfig: '{ "router_virtual_id": "11" }' It does not overwrite the original entry, instead producing the config:

```
vrrp_instance helloworld/helloworld {
  interface ens192
  virtual_router_id 1
  virtual_ipaddress {
    13.37.13.37
  }

  virtual_router_id 10
}
```

Which leads to more issues.

**Comment by raffaelespazzoli** [comment]
each loadbalancer/externalIP service gets a different `virtual_router_id`, the operator assumes that all of the 255 are available in the subnet where the operator runs.
To allow for the operator to run in subnets where other ipfailover instances are running I think the best approach would be to pass a list of unavailable of virtual_router_ids in the CR. This will reduce the number of supportable services, but should allow for the coexistence.
Also see this on allowing enabling support for more than 255 services.
