### ISSUE TITLE
Tolerations for KeepalivedGroup

### ISSUE THREAD

**Issue by danielkucera** [redhat-cop/keepalived-operator#30]
We need to run keepalived on nodes with taints.

This means we either need the operator to create keepalived daemon set with absolute tolerations:
```
tolerations:
 - operator: Exists
```
or to be able to specify tolerations in the CRD.

Could you implement this?

**Comment by danielkucera** [comment]
Another option would be mentioning in the readme that the template file can be completely overriden e.g. by mounting it from ConfigMap

**Comment by raffaelespazzoli** [comment]
close by #42
