### ISSUE TITLE
separate one Class C segment per KeepalivedGroup

### ISSUE THREAD

**Issue by ooichman** [redhat-cop/keepalived-operator#37]
In our disconnected environment we have a need to separate one Class C segment per KeepalivedGroup. Although we can create an interface per node per segment and specify the appropriate network interface within KeepalivedGroup, all groups take IP addresses from a single pool ('autoAssignedCIDRs' field within the network.config.openshift.io object). Therefore there is no guarantee one KeepalivedGroup won't use an address from a segment designated to another KeepalivedGroup's interface.

**Comment by raffaelespazzoli** [comment]
@ooichman you have a valid point. There is no ability to assign CIDRs to class of services identified say by labels. This would be an interesting feature to have, but again this is an RFE first to OCP, then when OCP models in some shape or form the fact that you can have multiple class of services, we can make this operator work with it.
In the meantime I suggest using externaIPs. This will require coordination from your tenants, but it should allow you to work.

**Comment by raffaelespazzoli** [comment]
can I close this?
