### ISSUE TITLE
Client IP addresses

### ISSUE THREAD

**Issue by foosinn** [redhat-cop/keepalived-operator#51]
The pods behind the service seem to see an internal Kubernetes IP address as client instead of the clients real IP.

Is this behavior wanted or changeable?

Thanks!

**Comment by raffaelespazzoli** [comment]
which IP address do you see?

I didn't give much thought to this behavior, but I don't think I can do much to change it.

**Comment by foosinn** [comment]
I see the nodes `tun0` IP. For example `10.131.x.1`.

It's quite a downside when running an Ingress Controller.

**Comment by raffaelespazzoli** [comment]
got it. No I don't think I can do anything about it.
Metallb may be able to solve this issue: https://metallb.universe.tf/

**Comment by foosinn** [comment]
I did try a few different things, but it seems like metallb is currently the only solution.

Thanks for pointing that out!
