### ISSUE TITLE
Multiple IP address created when only 1 is requested.

### ISSUE THREAD

**Issue by osirisstar-hub** [redhat-cop/keepalived-operator#52]
Working in an openshift environment.   Only 1 out of 3 clusters exhibit this problem.  

[root@mtaylor-rh81 iperftest]# oc new-project iperftest
Already on project "iperftest" on server "https://api.ocp4dev01.meteorcomm.lan:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app django-psql-example

to build a new example application in Python. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node

[root@mtaylor-rh81 iperftest]# oc apply -f iperf1-svc.yaml
service/iperf1 created
[root@mtaylor-rh81 iperftest]# oc get svc
NAME     TYPE           CLUSTER-IP       EXTERNAL-IP                           PORT(S)           AGE
iperf1   LoadBalancer   172.30.151.208   **10.22.4.109,10.22.4.104,10.22.4.109**   25000:31415/TCP   2s

[root@mtaylor-rh81 iperftest]# cat iperf1-svc.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    keepalived-operator.redhat-cop.io/keepalivedgroup: keepalived-operator/keepalivedgroup-workers
  labels:
    app: iperf
  name: iperf1
  namespace: iperftest
spec:
  externalIPs:
    - 10.22.4.104
  ports:
  - port: 25000
    protocol: TCP
    targetPort: 25000
  selector:
    app: iperf1
  sessionAffinity: ClientIP
  type: LoadBalancer

**Comment by raffaelespazzoli** [comment]
this behavior has nothing to do with the operator. you are creating a Service of type LoadBalancer service and requesting an ExternalIP, therefore you get two IPs. Change the service to ClusterIP and you'll get just the ExternalIP.

**Comment by osirisstar-hub** [comment]
This does not happen on any other cluster and the type loadbalancer is needed in order for keepalive to function.

**Comment by osirisstar-hub** [comment]
The loadbalancer type is what is in the readme for keepalived operator:

oc patch service django-psql-example -n test-keepalived-operator -p '{"spec":{"type":"LoadBalancer"}}' --type=strategic

**Comment by osirisstar-hub** [comment]
I think this has changed since I first implemented keepalive in this clustger.   

I see ingress.ip instead of external.ip.    So if we use external IP will it still be HA without the loadbalancer type?

**Comment by osirisstar-hub** [comment]
I see your point now.  Closing this issue.
