### ISSUE TITLE
config-reloader issue in latest release

### ISSUE THREAD

**Issue by brogger71** [redhat-cop/keepalived-operator#63]
Hi all,

There seams to be an issue in the latest keepalived release (keepalived-operator.v1.2.2). The container "config-reloader" crashloops with the following error:

/usr/local/bin/notify.sh: line 20: create_config_only: unbound variable

and yes, the var "create_config_only" is not set in the deamonset. Do i miss something?

Thanks,
Michael

**Comment by raffaelespazzoli** [comment]
the last release broke something. please upgrade to 1.3.0, it should fix everything. Apologies.

**Comment by madchr1st** [comment]
The latest release available in the OperatorHub (OCP 4.6.22) is 1.2.2, which uses the script from 1.3.0, but the container is not run with the necessary argument for `create_config_only`.

**Comment by raffaelespazzoli** [comment]
@madchr1st thanks, the 1.3.0 release is stuck in the community operator pipeline. Give me some time to sort that out.

**Comment by raffaelespazzoli** [comment]
The v1.3.0 release has been successfully shipped to OperatorHub, it should become available in your clusters shortly. Let me know how it goes.

**Comment by brogger71** [comment]
already successfully deployed here and working. No further issues so far. Thank you!

**Comment by raffaelespazzoli** [comment]
good, I'm going to close this then.
