### ISSUE TITLE
Keepalive conflicting with kube-proxy resulting in 404: no page found error

### ISSUE THREAD

**Issue by osirisstar-hub** [redhat-cop/keepalived-operator#68]
Upgraded openshift to 4.7 and now get issues where kube-proxy is not properly routing messages from the external IP to the internal service.

For example:  
   curl 10.22.4.97:10010
   404: Page Not Found

kube-proxy claims that the IP is already in use:

Warning  listen tcp4 10.22.4.97:10010: bind: address already in use  36s (x39 over 84m)     kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.97:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.97:10010: bind: address already in use.

**Comment by raffaelespazzoli** [comment]
ok, I need to understand more information.
1. can you share your keepalivedgroup CR
2. can you share your node layout `oc get nodes --show-labels
3. can you share the generated configmap in the keepalivedgroup CR namespace
4. can you share the externalIP service with the annotation
5. can you share the configuration you made on OCP network to enable externalIP services
6. finally where do you see that log exactly?

**Comment by osirisstar-hub** [comment]
Thanks.  

Here is the CR:
apiVersion: redhatcop.redhat.io/v1alpha1
kind: KeepalivedGroup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"redhatcop.redhat.io/v1alpha1","kind":"KeepalivedGroup","metadata":{"annotations":{},"name":"keepalivedgroup-workers","namespace":"keepalived-operator"},"spec":{"interface":"ens192","nodeSelector":{"node-role.kubernetes.io/worker":""}}}
  creationTimestamp: "2021-04-19T20:59:57Z"
  generation: 1
  managedFields:
  - apiVersion: redhatcop.redhat.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:image: {}
        f:interface: {}
        f:nodeSelector:
          .: {}
          f:node-role.kubernetes.io/worker: {}
    manager: oc
    operation: Update
    time: "2021-04-19T20:59:57Z"
  - apiVersion: redhatcop.redhat.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:interfaceFromIP: {}
        f:passwordAuth:
          .: {}
          f:secretKey: {}
          f:secretRef: {}
      f:status:
        .: {}
        f:conditions:
          .: {}
          k:{"type":"ReconcileError"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:observedGeneration: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"ReconcileSuccess"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:observedGeneration: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:routerIDs:
          .: {}
          f:deepa-eetest/external-classd-endpoint-0: {}
          f:deepa-eetest/zrr-backoffice-rbx-0: {}
    manager: manager
    operation: Update
    time: "2021-06-01T18:54:44Z"
  name: keepalivedgroup-workers
  namespace: keepalived-operator
  resourceVersion: "106030501"
  selfLink: /apis/redhatcop.redhat.io/v1alpha1/namespaces/keepalived-operator/keepalivedgroups/keepalivedgroup-workers
  uid: 88b67461-388e-4015-a83d-9271a4d2c65b
spec:
  image: registry.redhat.io/openshift4/ose-keepalived-ipfailover
  interface: ens192
  nodeSelector:
    node-role.kubernetes.io/worker: ""
status:
  conditions:
  - lastTransitionTime: "2021-06-01T19:17:48Z"
    message: ""
    observedGeneration: 1
    reason: LastReconcileCycleSucceded
    status: "True"
    type: ReconcileSuccess
  - lastTransitionTime: "2021-05-20T23:30:16Z"
    message: 'Operation cannot be fulfilled on daemonsets.apps "keepalivedgroup-workers": the object has been modified; please apply your changes to the latest version and try again'
    observedGeneration: 1
    reason: LastReconcileCycleFailed
    status: "True"
    type: ReconcileError
  routerIDs:
    deepa-eetest/external-classd-endpoint-0: 2
    deepa-eetest/zrr-backoffice-rbx-0: 1


Here are the nodes:
[root@mtaylor-rh81 scripts]# oc get nodes --show-labels
NAME                                           STATUS   ROLES    AGE   VERSION           LABELS
seaocp47dev01mst01.ocp47dev01.meteorcomm.lan   Ready    master   46d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01mst01.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/master=,node.openshift.io/os_id=rhcos
seaocp47dev01mst02.ocp47dev01.meteorcomm.lan   Ready    master   46d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01mst02.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/master=,node.openshift.io/os_id=rhcos
seaocp47dev01mst03.ocp47dev01.meteorcomm.lan   Ready    master   46d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01mst03.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/master=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk01.ocp47dev01.meteorcomm.lan   Ready    worker   46d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk01.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos,stim=true
seaocp47dev01wrk02.ocp47dev01.meteorcomm.lan   Ready    worker   46d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk02.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos,stim=true
seaocp47dev01wrk03.ocp47dev01.meteorcomm.lan   Ready    worker   36d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk03.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos,stim=true
seaocp47dev01wrk04.ocp47dev01.meteorcomm.lan   Ready    worker   21d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk04.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk05.ocp47dev01.meteorcomm.lan   Ready    worker   21d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk05.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk06.ocp47dev01.meteorcomm.lan   Ready    worker   21d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk06.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk07.ocp47dev01.meteorcomm.lan   Ready    worker   25d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk07.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk08.ocp47dev01.meteorcomm.lan   Ready    worker   25d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk08.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk09.ocp47dev01.meteorcomm.lan   Ready    worker   25d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk09.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk10.ocp47dev01.meteorcomm.lan   Ready    worker   25d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk10.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk11.ocp47dev01.meteorcomm.lan   Ready    worker   25d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk11.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk12.ocp47dev01.meteorcomm.lan   Ready    worker   11d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk12.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk13.ocp47dev01.meteorcomm.lan   Ready    worker   11d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk13.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos
seaocp47dev01wrk14.ocp47dev01.meteorcomm.lan   Ready    worker   11d   v1.20.0+7d0a2b2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=seaocp47dev01wrk14.ocp47dev01.meteorcomm.lan,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.openshift.io/os_id=rhcos


Here is the configmap for KG:

apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 03846a46.redhat.io
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-19T21:40:55Z"
  labels:
    operators.coreos.com/keepalived-operator.keepalived-operator: ""
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:controller_manager_config.yaml: {}
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"5915a322-a1d9-4c7b-819d-a92020ccd035"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
    manager: catalog
    operation: Update
    time: "2021-04-21T08:58:32Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:operators.coreos.com/keepalived-operator.keepalived-operator: {}
    manager: olm
    operation: Update
    time: "2021-04-21T08:58:33Z"
  name: keepalived-operator-manager-config
  namespace: keepalived-operator
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: keepalived-operator.v1.3.1
    uid: 5915a322-a1d9-4c7b-819d-a92020ccd035
  resourceVersion: "2119993"
  selfLink: /api/v1/namespaces/keepalived-opertor/configmaps/keepalived-operator-manager-config


Here is the service that gets bind errors:


apiVersion: v1
kind: Service
metadata:
  annotations:
    keepalived-operator.redhat-cop.io/keepalivedgroup: keepalived-operator/keepalivedgroup-workers
  creationTimestamp: "2021-06-01T17:05:56Z"
  labels:
    app: zrr-backoffice
    managed-by: backoffice-operator
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:keepalived-operator.redhat-cop.io/keepalivedgroup: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:type: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-06-01T18:54:44Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:managed-by: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"9e330875-43a5-4675-8007-42de39d403a9"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:externalIPs: {}
        f:ports:
          .: {}
          k:{"port":10010,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:managed-by: {}
          f:service-tag: {}
        f:sessionAffinity: {}
    manager: backoffice-operator
    operation: Update
    time: "2021-06-01T19:17:47Z"
  name: zrr-backoffice-rbx-0
  namespace: deepa-eetest
  ownerReferences:
  - apiVersion: itcm.meteorcomm.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: IpelmService
    name: rbx-0
    uid: 9e330875-43a5-4675-8007-42de39d403a9
  resourceVersion: "106030260"
  selfLink: /api/v1/namespaces/deepa-eetest/services/zrr-backoffice-rbx-0
  uid: f1bb150e-29e1-4bfa-89f7-886df6611a80
spec:
  clusterIP: 172.30.118.29
  clusterIPs:
  - 172.30.118.29
  externalIPs:
  - 10.22.4.98
  ports:
  - port: 10010
    protocol: TCP
    targetPort: 10010
  selector:
    app: zrr-backoffice
    managed-by: back



Here is the network configuration:

spec:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  externalIP:
    policy:
      allowedCIDRs:
      - 10.22.4.100/27
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16


I see the logs in the default project with oc get events.   Also see it in the describe of a node.

16m         Warning   listen tcp4 10.22.4.108:10010: bind: address already in use            node/seaocp47dev01wrk14.ocp47dev01.meteorcomm.lan   can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.108:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.108:10010: bind: address already in use

**Comment by raffaelespazzoli** [comment]
ok, a few more things
1. the configmap is not the right one, there should be one called `keepalivedgroup-workers`.
2. can you share the CIDR of the nodes.
3. do your nodes have a NIC called ens192? (not sure this matters....)
4. can I see a pod selected by 
```yaml
  selector:
    app: zrr-backoffice
    managed-by: back
```
just as a piece of advice the keepalivedgroup should not live in the same namespace as the keepalived operator. It is in general a bad idea to put operators and operands in the same namespace.

**Comment by osirisstar-hub** [comment]
Here is that configmap:


apiVersion: v1
data:
  keepalived.conf: "global_defs {\n    router_id keepalivedgroup-workers\n              \n}\n\n\n\n\n\n\nvrrp_instance itcm4training/ag-1 {\n    interface enp1s0\n    \n    virtual_router_id 1  \n    \n    virtual_ipaddress {\n      \n      192.168.130.29\n      \n    }\n\n    \n}\n\n\nvrrp_instance itcm4training/ag-2 {\n    interface enp1s0\n    \n    virtual_router_id 2  \n    \n    virtual_ipaddress {\n      \n      192.168.130.26\n      \n    }\n\n    \n}\n\n\nvrrp_instance itcm4training/ag-3 {\n    interface enp1s0\n    \n    virtual_router_id 4  \n    \n    virtual_ipaddress {\n      \n      192.168.130.30\n      \n    }\n\n    \n}\n\n\nvrrp_instance itcm4training/backoffice-1-ipelmpool-1 {\n    interface enp1s0\n    \n    virtual_router_id 3  \n    \n    virtual_ipaddress {\n      \n      192.168.130.27\n      \n    }\n\n    \n}\n\n\nvrrp_instance itcm4training/test-appb-amqpapp-001-service {\n    interface enp1s0\n    \n    virtual_router_id 5  \n    \n    virtual_ipaddress {\n      \n      192.168.130.28\n      \n    }\n\n    \n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-14T22:03:26Z"
  labels:
    keepalivedGroup: keepalivedgroup-workers
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:keepalived.conf: {}
      f:metadata:
        f:labels:
          .: {}
          f:keepalivedGroup: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"cb71fd72-95ba-4201-81b1-c691ccefa79b"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
    manager: manager
    operation: Update
    time: "2021-05-14T22:03:26Z"
  name: keepalivedgroup-workers
  namespace: keepalived-operator
  ownerReferences:
  - apiVersion: redhatcop.redhat.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: KeepalivedGroup
    name: keepalivedgroup-workers
    uid: cb71fd72-95ba-4201-81b1-c691ccefa79b
  resourceVersion: "5718563"
  selfLink: /api/v1/namespaces/keepalived-operator/configmaps/keepalivedgroup-workers
  uid: 26526459-8946-4866-b213-6c2e01b6edcc

CIDR for the default route:
    10.22.4.0/22


Yes definitely the nodes have ens192 - the IP does ping.

2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8a:78:06 brd ff:ff:ff:ff:ff:ff
    inet 10.22.5.21/22 brd 10.22.7.255 scope global dynamic noprefixroute ens192
       valid_lft 4158916sec preferred_lft 4158916sec
    inet6 fe80::663d:70d5:ca42:4f17/64 scope link noprefixroute
       valid_lft forever preferred_lft forever


Here are the selector results:

[root@mtaylor-rh81 ~]# oc get pod --selector app=zrr-backoffice --selector managed-by=backoffice-operator --selector service-tag=zrr-backoffice-rbx-0
NAME                     READY   STATUS    RESTARTS   AGE
rbx-0-578797fbd6-7gtz7   1/1     Running   0          50m

Which matches the service:
  selector:
    app: zrr-backoffice
    managed-by: backoffice-operator
    service-tag: zrr-backoffice-rbx-0


When the selectors don't align we get connection refused.  In this case we get page not found because kube-proxy is not routing things properly.

**Comment by osirisstar-hub** [comment]
FYI: I found the node where the conflict was occurring and killed the keepalive work on that node.  After doing that the external IP and port began working as expected.  I doubt it will stay up.

**Comment by osirisstar-hub** [comment]
Actually it stopped working after about 5 minutes and then several nodes apparently had the same IP address.

**Comment by osirisstar-hub** [comment]
IP address is: 10.22.4.104


seaocp47dev01wrk06.ocp47dev01.meteorcomm.lan
  ExternalIP:  10.22.5.26
  ExternalIP:  10.22.4.104
  Warning  listen tcp4 10.22.4.104:10010: bind: address already in use  7m37s (x25 over 8m16s)  kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.104:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.104:10010: bind: address already in use
seaocp47dev01wrk07.ocp47dev01.meteorcomm.lan
  ExternalIP:  10.22.5.27
seaocp47dev01wrk08.ocp47dev01.meteorcomm.lan
  ExternalIP:  10.22.5.28
  Warning  listen tcp4 10.22.4.102:10001: bind: cannot assign requested address  145m (x9 over 7d)     kube-proxy  can't open "externalIP for deepa-eetest/external-classd-endpoint-0" (10.22.4.102:10001/tcp), skipping this externalIP: listen tcp4 10.22.4.102:10001: bind: cannot assign requested address
  Warning  listen tcp4 10.22.4.97:10010: bind: address already in use            124m (x19 over 124m)  kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.97:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.97:10010: bind: address already in use
seaocp47dev01wrk09.ocp47dev01.meteorcomm.lan
  ExternalIP:  10.22.5.29
  ExternalIP:  10.22.4.104
  Warning  listen tcp4 10.22.4.99:10010: bind: address already in use   85m (x6 over 85m)      kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.99:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.99:10010: bind: address already in use
  Warning  listen tcp4 10.22.4.104:10010: bind: address already in use  7m59s (x25 over 9m3s)  kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.104:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.104:10010: bind: address already in use
seaocp47dev01wrk10.ocp47dev01.meteorcomm.lan
  ExternalIP:  10.22.5.30
seaocp47dev01wrk11.ocp47dev01.meteorcomm.lan
  ExternalIP:  10.22.5.31
  Warning  listen tcp4 10.22.4.101:10010: bind: address already in use  116m (x7 over 116m)   kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.101:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.101:10010: bind: address already in use
  Warning  listen tcp4 10.22.4.108:10010: bind: address already in use  115m (x14 over 115m)  kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.108:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.108:10010: bind: address already in use
seaocp47dev01wrk12.ocp47dev01.meteorcomm.lan
  ExternalIP:  10.22.5.32
  ExternalIP:  10.22.4.104
  Warning  listen tcp4 10.22.4.95:10010: bind: address already in use           116m                    kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.95:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.95:10010: bind: address already in use
  Warning  listen tcp4 10.22.4.95:10010: bind: cannot assign requested address  116m                    kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.95:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.95:10010: bind: cannot assign requested address
  Warning  listen tcp4 10.22.4.104:10010: bind: address already in use          7m43s (x25 over 8m56s)  kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.104:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.104:10010: bind: address already in use
seaocp47dev01wrk13.ocp47dev01.meteorcomm.lan
  ExternalIP:  10.22.5.33
  ExternalIP:  10.22.4.104
  ExternalIP:  10.22.4.102
  ExternalIP:  10.22.4.98
  Warning  listen tcp4 10.22.4.97:10010: bind: address already in use           124m (x12 over 124m)   kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.97:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.97:10010: bind: address already in use
  Warning  listen tcp4 10.22.4.97:10010: bind: cannot assign requested address  124m                   kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.97:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.97:10010: bind: cannot assign requested address
  Warning  listen tcp4 10.22.4.99:10010: bind: address already in use           85m (x6 over 159m)     kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.99:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.99:10010: bind: address already in use
  Warning  listen tcp4 10.22.4.104:10010: bind: address already in use          9m5s (x238 over 22m)   kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.104:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.104:10010: bind: address already in use
  Warning  listen tcp4 10.22.4.98:10010: bind: address already in use           4m27s (x37 over 103m)  kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.98:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.98:10010: bind: address already in use
seaocp47dev01wrk14.ocp47dev01.meteorcomm.lan
  ExternalIP:  10.22.5.34
  ExternalIP:  10.22.4.104
  Warning  listen tcp4 10.22.4.97:10010: bind: address already in use   118m (x326 over 3h27m)  kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.97:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.97:10010: bind: address already in use
  Warning  listen tcp4 10.22.4.108:10010: bind: address already in use  108m (x299 over 115m)   kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.108:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.108:10010: bind: address already in use
  Warning  listen tcp4 10.22.4.98:10010: bind: address already in use   63m (x620 over 3h33m)   kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.98:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.98:10010: bind: address already in use
  Warning  listen tcp4 10.22.4.99:10010: bind: address already in use   58m (x916 over 3h19m)   kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.99:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.99:10010: bind: address already in use
  Warning  listen tcp4 10.22.4.104:10010: bind: address already in use  8m57s (x694 over 56m)   kube-proxy  can't open "externalIP for deepa-eetest/zrr-backoffice-rbx-0" (10.22.4.104:10010/tcp), skipping this externalIP: listen tcp4 10.22.4.104:10010: bind: address already in use

**Comment by osirisstar-hub** [comment]
This turned out to be a very odd port conflict on the node.  Port 10010 is in use as a TCP6 socket but for some reason kube-proxy wouldn't bind on that port even though we are using TCP4.
