### ISSUE TITLE
New keepalived operator v1.3.2  fails to install in openshift.

### ISSUE THREAD

**Issue by osirisstar-hub** [redhat-cop/keepalived-operator#69]
New version is trying to replace v1.3.1 and is failing across all of my openshift clusters.

Install strategy failed: Deployment.apps "keepalived-operator-controller-manager" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"operator":"keepalived-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Comment by raffaelespazzoli** [comment]
please see this: https://github.com/redhat-cop/cert-utils-operator/issues/92 . it's the same issue. Sorry for the inconvenience.

**Comment by osirisstar-hub** [comment]
yes - that works for me.  Thanks.
